# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'Hackathon' do

    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'NSDate-Extensions-iOS7', :git => 'https://github.com/HiTask/NSDate-Extensions.git'
    pod 'UIImage-ResizeMagick'
    pod 'NSTimer-Blocks', '~> 0.0'
    pod 'SDWebImage', '~>3.7'
    pod 'KeychainAccess'
    pod 'ObjectMapper'
    pod 'JLRoutes'
    pod 'IDMPhotoBrowser'
    pod 'Google/CloudMessaging'
    
end